// products.js
const product = [
  { name: 'AirPods Pro (2nd Gen)', price: 249.00, image: "images/products/AirPods Pro (2nd Gen).jpg", type: 'Accessories' },
  { name: 'Anker 735 Charger (Nano II 65W)', price: 399.00, image: "images/products/Anker 735 Charger (Nano II 65W).jpg", type: 'Accessories' },
  { name: 'Apple MagSafe Charger', price: 129.00, image: "images/products/Apple MagSafe Charger.jpg", type: 'Accessories' },
  { name: 'Belkin BoostCharge Pro 3-in-1', price: 199.00, image: "images/products/Belkin BoostCharge Pro 3-in-1.jpg", type: 'Accessories' },
  { name: 'Dell XPS 15', price: 2499.00, image: "images/products/Dell XPS 15.jpg", type: 'Laptops' },
  { name : 'Dyson Pure Cool TP07', price: 599.00, image: "images/products/Dyson Pure Cool TP07.jpg", type: 'Accessories' }, 
  {name : 'Google Pixel 7 Pro', price: 899.00, image: "images/products/Google Pixel 7 Pro.jpg", type: 'Smartphones' },
  { name : 'Hessaire MC37M Evaporative Cooler'  , price: 299.00, image: "images/products/Hessaire MC37M Evaporative Cooler.jpg", type: 'Accessories' }, 
  {name : 'Hisense U8H Quantum ULED', price: 1299.00, image: "images/products/Hisense U8H Quantum ULED.jpg", type: 'Tv'} ,
  {name : 'Honeywell Portable AC', price: 499.00, image: "images/products/Honeywell Portable AC.jpg", type: 'Accessories' },
  {name : 'iPhone 14 Pro Max', price: 1099.00, image: "images/products/iPhone 14 Pro Max.jpg", type: 'Smartphones' },
  {name : 'iPhone 14' , price: 799.00, image: "images/products/iPhone 14.jpg", type: 'Smartphones' },
  {name : 'Lamicall Adjustable Phone Stand' , price: 29.99, image: "images/products/Lamicall Adjustable Phone Stand.jpg", type: 'Accessories' },
  {name : 'LG C2 OLED evo'  , price: 1999.00, image: "images/products/LG C2 OLED evo.jpg", type: 'Tv' },
  {name : 'LG Dual Inverter AC', price: 599.00, image: "images/products/LG Dual Inverter AC.jpg", type: 'Accessories' },
  {name : 'Logitech MX Master 3S' , price: 99.99, image: "images/products/Logitech MX Master 3S.jpg", type: 'Accessories' },
  {name : 'mac book 16 pro', price: 2499.00, image: "images/products/macbook16pro.jpg", type: 'Laptops'},
  {name : 'OnePlus 11 5G', price: 899.00, image: "images/products/OnePlus 11 5G.jpg", type: 'Smartphones'} , 
  {name : 'Samsung Galaxy S23 Ultra', price: 1199.00, image: "images/products/Samsung Galaxy S23 Ultra.jpg", type: 'Smartphones' },
  {name : 'Samsung Galaxy Watch 5 Pro', price: 449.00, image: "images/products/Samsung Galaxy Watch 5 Pro.jpg", type: 'Accessories' },
  {name : 'Samsung QN90B Neo QLED', price: 1799.00, image: "images/products/Samsung QN90B Neo QLED.jpg", type: 'Tv' },
  {name : 'Samsung The Frame 2022', price: 1599.00, image: "images/products/Samsung The Frame.jpg", type: 'Tv' },
  {name : 'Samsung WindFree AC', price: 699.00, image: "images/products/Samsung WindFree AC.jpg", type: 'Accessories' },
  {name : 'Sony A95K QD-OLED', price: 2999.00, image: "images/products/Sony A95K QD-OLED.jpg", type: 'Tv' },
  {name : 'Sony WH-1000XM5 Headphones', price: 399.00, image: "images/products/Sony WH-1000XM5 Headphones.jpg", type: 'Accessories' },
  { name : 'Spigen Tough Armor Case for iPhone 14', price: 39.99, image: "images/products/Spigen Tough Armor Case for iPhone 14.jpg", type: 'Accessories' },
  {name : 'TCL 6-Series Roku TV', price: 899.00, image: "images/products/TCL 6-Series Roku TV.jpg", type: 'Tv'},
  {name : 'UGREEN USB C to Lightning Cable', price: 19.99, image: "images/products/UGREEN USB C to Lightning Cable.jpg", type: 'Accessories'}, 
  {name : 'Vornado 660 Whole Room Air Circulator', price: 99.99, image: "images/products/Vornado 660 Whole Room Air Circulator.jpg", type: 'Accessories'},
  { name : 'Xiaomi 13 Pro', price: 1099.00, image: "images/products/Xiaomi 13 Pro.jpg", type: 'Smartphones' },
];

export default product;
